name: Metrics

on:
  schedule:
    - cron: '0 0 * * *'
  
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }} 
          plugin_wakatime_url: https://wakapi.dev
          plugin_wakatime_user: ${{ github.repository_owner }} 
          plugin_wakatime_sections: time, projects, projects-graphs 
